-- MySQL Script generated by MySQL Workbench
-- Tue Jun 30 18:18:52 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema kalimba_musica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kalimba_musica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kalimba_musica` DEFAULT CHARACTER SET utf8mb4 ;
USE `kalimba_musica` ;

-- -----------------------------------------------------
-- Table `kalimba_musica`.`brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kalimba_musica`.`brands` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `kalimba_musica`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kalimba_musica`.`categories` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `kalimba_musica`.`colors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kalimba_musica`.`colors` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `kalimba_musica`.`subcategories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kalimba_musica`.`subcategories` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `categories_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `category_id_idx` (`categories_id` ASC),
  CONSTRAINT `fk_subcategories_categories_id`
    FOREIGN KEY (`categories_id`)
    REFERENCES `kalimba_musica`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `kalimba_musica`.`guides`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kalimba_musica`.`guides` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(10000) NOT NULL,
  `subcategories_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `types_id_idx` (`subcategories_id` ASC),
  CONSTRAINT `fk_guides_subcategories_id`
    FOREIGN KEY (`subcategories_id`)
    REFERENCES `kalimba_musica`.`subcategories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `kalimba_musica`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kalimba_musica`.`products` (
  `name` VARCHAR(100) NOT NULL,
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `price` DECIMAL(2,0) NOT NULL,
  `discount` INT(11) NULL DEFAULT 0,
  `stock` TINYINT(4) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `categories_id` INT(11) NOT NULL,
  `subcategories_id` INT(11) NOT NULL,
  `brands_id` INT(11) NOT NULL,
  `colors_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `brands_id_idx` (`brands_id` ASC),
  INDEX `category_id_idx` (`categories_id` ASC),
  INDEX `types_id_idx` (`subcategories_id` ASC),
  INDEX `colors_id_idx` (`colors_id` ASC),
  CONSTRAINT `fk_products_brands_id`
    FOREIGN KEY (`brands_id`)
    REFERENCES `kalimba_musica`.`brands` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_categories_id`
    FOREIGN KEY (`categories_id`)
    REFERENCES `kalimba_musica`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_colors_id`
    FOREIGN KEY (`colors_id`)
    REFERENCES `kalimba_musica`.`colors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_subcategories_id`
    FOREIGN KEY (`subcategories_id`)
    REFERENCES `kalimba_musica`.`subcategories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `kalimba_musica`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kalimba_musica`.`images` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `products_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `products_id_idx` (`products_id` ASC),
  CONSTRAINT `fk_images_products_id`
    FOREIGN KEY (`products_id`)
    REFERENCES `kalimba_musica`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `kalimba_musica`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kalimba_musica`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `role` INT(11) NOT NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `tel` INT(11) NULL DEFAULT NULL,
  `birth_date` DATE NULL DEFAULT NULL,
  `username` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `image` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `kalimba_musica`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kalimba_musica`.`orders` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `shipping_city` VARCHAR(100) NOT NULL,
  `shipping_postalcode` INT(11) NOT NULL,
  `shipping_date` DATE NULL DEFAULT NULL,
  `users_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `users_id_idx` (`users_id` ASC),
  CONSTRAINT `fk_orders_users_id`
    FOREIGN KEY (`users_id`)
    REFERENCES `kalimba_musica`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `kalimba_musica`.`orders_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kalimba_musica`.`orders_products` (
  `orders_id` INT(11) NOT NULL,
  `products_id` INT(11) NOT NULL,
  INDEX `products_id_idx` (`products_id` ASC),
  INDEX `orders_id_idx` (`orders_id` ASC),
  CONSTRAINT `fk_ordersproducts_orders_id`
    FOREIGN KEY (`orders_id`)
    REFERENCES `kalimba_musica`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordersproducts_products_id`
    FOREIGN KEY (`products_id`)
    REFERENCES `kalimba_musica`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
